theme = "duckquill"

title = "Matteo Risso"
base_url = "https://matteorisso.github.io"
description = "Well, Hi"

compile_sass = true
minify_html = true
build_search_index = false

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]

smart_punctuation = true
external_links_target_blank = true

[extra]
# Sets theme and browser theme color.
# See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
primary_color = "#ffd061"
# primary_color = "#c58223"
primary_color_alpha = "rgba(227, 186, 143, 0.6)"
# Ditto but for the dark mode.
# If not set regular variant will be used.
primary_color_dark = "#ff7800"
primary_color_dark_alpha = "rgba(255, 120, 0, 0.2)"
# URL to website's source code
source_url = "https://github.com/matteorisso/matteorisso.github.io/tree/main"
# Whether to show "copy code" button on all code blocks
# that have the language set.
# See https://www.getzola.org/documentation/content/syntax-highlighting/
show_copy_button = true
# Whether to show estimated read time in posts.
# Calculated using the simple math: number of words รท words per minute.
show_read_time = true
# words_per_minute = "200"

[extra.nav]

icons = true
links = [
  { url = "@/blog/_index.md", name = "Blog" },
  { url = "@/section/index.md", name = "Section" },
  { url = "http://github.com/matteorisso", name = "", icon = "github" },
]

# socials = [
# ]
